# Generated by Django 5.1.1 on 2024-10-06 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('quality', models.IntegerField()),
                ('interval', models.IntegerField()),
                ('ease_factor', models.FloatField()),
                ('user_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.usercard')),
            ],
        ),
    ]
